services:
  - type: web
    name: idaconf-bbb
    runtime: ruby
    plan: free
    region: frankfurt
    branch: main
    buildCommand: bundle install && yarn install --ignore-engines && bundle exec rails assets:precompile
    startCommand: bin/rails db:migrate && bin/rails server -p $PORT
    envVars:
      - key: SECRET_KEY_BASE
        value: 12f0036d97c66093f525e306e4a7d5de24422d714e8be4f766eaf37e4fa76e153aaf07e61996c09354b1214ae9b39297da0f2beb590a4aeb5b4a6e77d42a488a
      - key: BIGBLUEBUTTON_ENDPOINT
        value: https://test-install.blindsidenetworks.com/bigbluebutton/api
      - key: BIGBLUEBUTTON_SECRET
        value: 8cd8ef52e8e101574e400365b55e11a6
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: BUNDLE_FROZEN
        value: "false"
      - key: PGSSLMODE
        value: require
      - key: ALLOWED_DOMAINS
        value: "*"
      - key: DATABASE_URL
        value: postgres://greenlight_gwab_user:dfcT9eqeHSq6sm19UJiuDB75BhJ6o3GW@dpg-d9j5e5beo5us73asqtv0-a.frankfurt-postgres.render.com/greenlight_gwab?sslmode=require
